mainsite/urls.py
from django.conf.urls import url
from .views import index, post

app_name = 'mainsite'
urlpatterns = [
    url(r'^$', view=index),
    url(r'^index/$', view=index, name='index'),
    url(r'^post/(?P<post_id>[0-9]+)/$', view=post, name='post'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mainsite.urls'))
]

mainsite/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField('Name', max_length=30)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('Title', max_length=150)
    post_date = models.DateField('Date')
    tags = models.ManyToManyField(Tag)
    content = models.TextField('Content', default='Empty post')

    def __str__(self):
        return self.title

mainsite/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post


def index(request):
    return render(request=request, template_name='mainsite/index.html', context={'post_all': Post.objects.all()})


def post(request, post_id):
    post_object = get_object_or_404(Post, pk=post_id)
    return render(request=request, template_name='mainsite/post.html', context={'post_object': post_object})

mainsite/templates/mainsite/base.html
{% load staticfiles %}

<div id="header">
    <head>
        <meta charset="UTF-8">
        <title>Xelaweb - {% block title %}{% endblock %}</title>
    </head>
    <h1>This is a header!</h1>
    <script src="{% static 'mainsite/js/test.js' %}"></script>
</div>


<link rel="stylesheet" href="{% static 'mainsite/style.css' %}">

<div id="content">
    {% block content %}{% endblock %}
</div>


<div id="footer">
    <footer>
        All Rights Reserved®

    </footer>
</div>

mainsite/templates/mainsite/index.html
{% extends 'mainsite/base.html' %}


{% block title %}Index{% endblock %}

{% block content %}
    <body>
        <br>
        <ul>
            {% for post in post_all %}
            <li><a href="{% url 'mainsite:post' post.id %}">{{ post.title }}</a> {% for tag in post.tags.all %}{{ tag.name }}{% endfor %}</li>
            {% endfor %}
        </ul>
    </body>
{% endblock %}


mainsite/templates/mainsite/post.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}

{% block title %}{{ post_object.title }}{% endblock %}

{% block content %}
    <body>
        <br>
        <br>
        {{ post_object.content }}
    </body>
{% endblock %}